
@api = http://localhost:4000/clientes


GET {{api}}

###

POST {{api}}
Content-Type: application/json

{
    "nombre": "dfgfdg",
    "apellido_paterno": "gjy",
    "apellido_materno": "yjuy",
    "rfc": "123456",
    "curp": "14785"
} 



###
GET {{api}}/1

###
DELETE  {{api}}/4

###

PUT  {{api}}/1
Content-Type: application/json

{
    "nombre": "David",
    "apellido_paterno": "Osornio",
    "apellido_materno": "Garcia",
    "rfc": "OOGD980325F75",
    "curp": "OOGD980325HMNSRV05"
}  
